name: Airhockey
version: '1.0-SNAPSHOT'
main: curio.nl.airhockey.Airhockey
api-version: '1.21'
commands:
  startgame:
    description: Starts the airhockey game
  endgame:
    description: Ends the airhockey game
  jointeam:
    description: Join a team
    usage: /jointeam <red|blue>

  premissions:
    airhockey.startgame:
      description: Allows the player to start the airhockey game
      default: false
    airhockey.endgame:
      description: Allows the player to end the airhockey game
      default: false
    airhockey.jointeam:
      description: Allows the player to join a team
      default: true